wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      4: 3.7.0
      5: 0.11.1
      8:
      - 3
      - 5
